[package]
name = "alkanes-build"
version.workspace = true
edition.workspace = true

[lib]
name = "alkanes_build"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
hex = "0.4"

[features]
native-deps = []

