[package]
name = "ordinals"
version = "0.5.2"
edition = "2021"
description = "Library for interoperating with ordinals and inscriptions"
homepage = "https://github.com/ordinals/ord"
repository = "https://github.com/ordinals/ord"
license = "CC0-1.0"
rust-version = "1.71.0"

[features]
dogecoin = []

[dependencies]
bitcoin = { version = "0.32.6", features = ["rand"] }
derive_more = { version = "0.99.17", features = ["display", "from_str"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_with = "2.3.3"
thiserror = "1.0.56"

[dev-dependencies]
serde_json = { version = "1.0.81", features = ["preserve_order"] }
pretty_assertions = "1.2.1"
