[package]
name = "ordinals"
version.workspace = true
edition.workspace = true
description = "Library for interoperating with ordinals and inscriptions"
homepage = "https://github.com/ordinals/ord"
repository.workspace = true
license = "CC0-1.0"
rust-version = "1.74.0"

[features]
dogecoin = []

[dependencies]
bitcoin = { workspace = true }
derive_more = { version = "1.0.0", features = ["display", "from_str"] }
serde = { workspace = true, features = ["derive"] }
serde_with = "3.7.0"
thiserror = "1.0.56"

[dev-dependencies]
serde_json = { workspace = true, features = ["preserve_order"] }
pretty_assertions = "1.2.1"
