[package]
name = "metashrew-core"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitcoin.workspace = true
bytes.workspace = true
cfg-if.workspace = true
wasm-bindgen.workspace = true
ordinals.workspace = true
prost.workspace = true
anyhow.workspace = true
wasm-bindgen-test.workspace = true
hex.workspace = true
metashrew-support = { path = "../metashrew-support" }
once_cell.workspace = true

[build-dependencies]
prost-build.workspace = true

[features]
test-utils = []
panic-hook = []
std = []
