[package]
name = "metashrew-core"
version.workspace = true
description = "metashrew indexer bindings"
repository = "https://github.com/sandshrewmetaprotocols/metashrew"
license = "MIT"
edition = "2021"
resolver = "2"



[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitcoin = "0.32.6"
bytes = "1.6.0"
cfg-if = "1.0.0"
ordinals = "0.0.8"
prost.workspace = true
anyhow = "1.0.89"
hex = "0.4.3"
metashrew-macros = { path = "../metashrew-macros" }
metashrew-cache = { path = "../metashrew-cache", features = ["sync"] }
metashrew-support = { path = "../metashrew-support" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.100"
getrandom = { version = "0.2", features = ["js"] }

[build-dependencies]
prost-build.workspace = true

[features]
default = []
test-utils = []
panic-hook = []
allocator = []
native-deps = []
