[package]
name = "metashrew-core"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true



[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitcoin.workspace = true
bytes = "1.6.0"
cfg-if = "1.0.0"
wasm-bindgen = "0.2.100"
ordinals.workspace = true
protobuf = "3"
anyhow = "1.0.89"
wasm-bindgen-test = "0.3.49"
hex = "0.4.3"
metashrew-support = { path = "../metashrew-support" }
once_cell.workspace = true

[build-dependencies]
protobuf-codegen = "3.4.0"
protoc-rust = { version = "2.28.0" }
protoc-bin-vendored = "3.0.0"

[features]
test-utils = []
panic-hook = []
