[package]
name = "alkanes-gpu-shader"
version = "0.5.2"
edition = "2021"
description = "GPU compute shader for alkanes parallel execution"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_arch = "spirv")'.dependencies]
spirv-std.workspace = true

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
spirv-std = { workspace = true, default-features = true }
alkanes-gpu = { path = "../alkanes-gpu" }

[package.metadata.rust-gpu.build]
capabilities = ["Int64", "Int16", "StorageBuffer16BitAccess"]
