# This is a meta-package that re-exports the serde crate
# The actual serde implementation is in the serde/ subdirectory

[package]
name = "alkanes-serde-meta"
version = "1.0.219"
edition = "2021"

# Re-export the actual serde crate
[dependencies]
serde = { path = "serde", default-features = false }

[lib]
name = "serde"
path = "src/lib.rs"
