[package]
name = "rockshrew-diff"
version.workspace = true
edition = "2021"

[[bin]]
name = "db_analyzer"
path = "src/main.rs"

[dependencies]
rocksdb = { version = "0.21.0", optional = true }
clap = { version = "4.5.4", features = ["derive"] }
anyhow = "1.0.82"
[features]
native-deps = ["rocksdb"]

