[package]
authors = ["Bryant Luk <code@bryantluk.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "leb128fmt-tests"
publish = false
version = "0.1.0"

[dependencies]
leb128fmt = { path = "../leb128fmt" }

[dev-dependencies]
proptest = "1.3.1"
