[package]
name = "protorune-support"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitcoin = { workspace = true }
serde = { workspace = true }
ordinals = { workspace = true }
anyhow = { workspace = true }
metashrew-support = { workspace = true }
hex = { workspace = true }
prost = { workspace = true }
bytes = { workspace = true }
bech32 = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }