[package]
name = "protorune-support"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
resolver = "2"

[lib]
crate-type = ["rlib"]

[dependencies]
bitcoin = { workspace = true }
serde = { workspace = true }
ordinals = { workspace = true }
anyhow = { workspace = true }
metashrew-core = { workspace = true }
metashrew-support = { workspace = true }
hex = { workspace = true }
protobuf = { workspace = true }
bech32 = "0.11.0"
once_cell = { workspace = true }

[build-dependencies]
protobuf-codegen = { workspace = true }
protoc-rust = { workspace = true }
protoc-bin-vendored = { workspace = true }
prost-build = { workspace = true }
protobuf = { workspace = true }

[features]
test-utils = []
mainnet = []
cache = []
