[package]
name = "protorune-support"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitcoin = { workspace = true }
serde = { workspace = true }
ordinals = { workspace = true }
anyhow = { workspace = true }
metashrew-support = { workspace = true }
hex = "0.4.3"
prost = { workspace = true }
bytes = { workspace = true }
bech32 = "0.11.0"

[build-dependencies]
prost-build = { workspace = true }

