[package]
name = "alkanes-native"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
metashrew-sync = { path = "../metashrew-sync", features = ["native-deps"] }
rocksdb = "0.21.0"
anyhow = "1.0.75"
bitcoincore-rpc = "0.19.0"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.77"
bitcoin = { workspace = true }
clap = { version = "4.5.4", features = ["derive"] }
alkanes-runtime = { path = "../alkanes-runtime" }
alkanes = { path = "../../" }
once_cell = "1.19.0"
metashrew-core = { path = "../metashrew-core" }
