package example:genesis-alkane-upgraded-eoa;

interface genesis-alkane-upgraded-eoa {
    initialize: func() -> result<_, string>;
    upgrade: func() -> result<_, string>;
    mint: func() -> result<_, string>;
    collect-fees: func() -> result<_, string>;
    burn: func(amount: u64) -> result<_, string>;
    get-name: func() -> result<string, string>;
    get-symbol: func() -> result<string, string>;
    get-total-supply: func() -> result<u64, string>;
}

world genesis-alkane-upgraded-eoa-world {
    export genesis-alkane-upgraded-eoa;
}
