[package]
name = "standalone-spirv-build"
version = "0.1.0"
edition = "2021"

[dependencies]
spirv-builder = { git = "https://github.com/EmbarkStudios/rust-gpu", rev = "7e54ed23" }

[[bin]]
name = "build"
path = "src/main.rs"