package example:genesis-protorune;

interface genesis-protorune {
    initialize: func() -> result<_, string>;
    mint: func() -> result<_, string>;
    get-name: func() -> result<string, string>;
    get-symbol: func() -> result<string, string>;
    get-total-supply: func() -> result<u64, string>;
}

world genesis-protorune-world {
    export genesis-protorune;
}
