[package]
name = "metashrew-support"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow.workspace = true
bech32.workspace = true
bitcoin.workspace = true
hex.workspace = true
prost.workspace = true
byteorder.workspace = true
downcast-rs = "1.2.0"


[build-dependencies]
anyhow.workspace = true
prost-build.workspace = true
flate2.workspace = true
hex.workspace = true