//! Test program for batch payment bytecode generation
//!
//! Run with: cargo run --example test_batch_bytecode --features experimental-asm

#[cfg(feature = "experimental-asm")]
use alkanes_cli_common::brc20_prog::generate_batch_payment_fetcher_bytecode;

#[cfg(feature = "experimental-asm")]
fn main() {
    env_logger::init();

    println!("Testing batch payment bytecode generation...\n");

    let frbtc_address = "0x1234567890123456789012345678901234567890";
    let cutoff_height = 1000u64;
    let oldest_utxo_height = 500u64;

    match generate_batch_payment_fetcher_bytecode(frbtc_address, cutoff_height, oldest_utxo_height) {
        Ok(bytecode) => {
            println!("✅ Successfully generated bytecode!");
            println!("   Length: {} bytes", bytecode.len() / 2);
            println!("   Bytecode: 0x{}", bytecode);
            println!("\n✅ Test passed!");
        }
        Err(e) => {
            eprintln!("❌ Failed to generate bytecode: {:?}", e);
            std::process::exit(1);
        }
    }
}

#[cfg(not(feature = "experimental-asm"))]
fn main() {
    eprintln!("This example requires the 'experimental-asm' feature.");
    eprintln!("Run with: cargo run --example test_batch_bytecode --features experimental-asm");
    std::process::exit(1);
}
