//! Test program for batch payment bytecode generation
//!
//! Run with: cargo run --example test_batch_bytecode

use alkanes_cli_common::brc20_prog::generate_batch_payment_fetcher_bytecode;

fn main() {
    env_logger::init();

    println!("Testing batch payment bytecode generation...\n");

    let frbtc_address = "0x1234567890123456789012345678901234567890";
    let cutoff_height = 1000u64;

    match generate_batch_payment_fetcher_bytecode(frbtc_address, cutoff_height) {
        Ok(bytecode) => {
            println!("✅ Successfully generated bytecode!");
            println!("   Length: {} bytes", bytecode.len() / 2);
            println!("   Bytecode: {}", bytecode);
            println!("\n✅ Test passed!");
        }
        Err(e) => {
            eprintln!("❌ Failed to generate bytecode: {:?}", e);
            std::process::exit(1);
        }
    }
}
