[package]
name = "protorune"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
protorune-support = { workspace = true }

[features]
cache = ["protorune-support/cache"]
mainnet = ["protorune-support/mainnet"]
test-utils = ["protorune-support/test-utils"]
