[package]
name = "protorune"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
test-utils = []
mainnet = []
cache = []

[dependencies]
metashrew-core = { path = "../metashrew-core", features = ["test-utils"] }
anyhow = { workspace = true }
bitcoin = { workspace = true }
metashrew-support = { workspace = true }
alkanes-support = { workspace = true }
protorune-support = { workspace = true }
ordinals = { workspace = true }
ruint = { workspace = true }
wasm-bindgen = { workspace = true }
byteorder = { workspace = true }
wasm-bindgen-test = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
hex = { workspace = true }
prost = { workspace = true }
bytes = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }

[dev-dependencies]
alkanes = { path = "../alkanes", features = ["test-utils"] }
