[package]
name = "protorune"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
test-utils = []
mainnet = []
cache = []

[dependencies]
anyhow = { workspace = true }
bitcoin = { workspace = true }
metashrew-core = { workspace = true }
metashrew-support = { workspace = true }
protorune-support = { workspace = true }
ordinals = { workspace = true }
ruint = { workspace = true }
wasm-bindgen = { workspace = true }
byteorder = { workspace = true }
wasm-bindgen-test = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
hex = { workspace = true }
protobuf = { workspace = true }

[dev-dependencies]
metashrew-core = { git = "https://github.com/sandshrewmetaprotocols/metashrew", features = ["test-utils"] }
wasm-bindgen-cli = "0.2.99"
getrandom = { version = "0.2.15", features = ["js"] }
protorune = { path = ".", features = ["test-utils"] }
