// This file serves as the entry point for the Web Worker.
// It's compiled as a separate Wasm module and is responsible for
// registering the `CryptoWorker` so that the main application can spawn it.

use crate::crypto_worker::CryptoWorker;
use gloo_worker::Registrable;
use wasm_bindgen::prelude::*;

#[wasm_bindgen(start)]
pub fn main() {
    // The `CryptoWorker` is generated by the `#[gloo_worker::reactor]` macro.
    // The `registrar()` method allows the worker to be registered and made
    // available to the main application.
    CryptoWorker::registrar().register();
}