mod gen_abi;
mod gen_client;
mod gen_dispatch;
mod gen_entry;
mod gen_trait;
mod gen_types;
mod type_utils;

use alkanes_wit_parser::AlkaneContractIR;
use anyhow::Result;
use std::path::Path;

/// Generated output for a single contract.
pub struct GeneratedContract {
    /// The main generated module file (includes everything).
    pub module_code: String,
}

/// Generate Rust code from an AlkaneContractIR.
pub fn generate(ir: &AlkaneContractIR) -> Result<GeneratedContract> {
    let custom_types = gen_types::generate_custom_types(ir);
    let contract_trait = gen_trait::generate_trait(ir);
    let dispatch = gen_dispatch::generate_dispatch(ir);
    let entry_points = gen_entry::generate_entry_points(ir);
    let clients = gen_client::generate_clients(ir);
    let abi = gen_abi::generate_abi_fn(ir);

    let tokens = quote::quote! {
        // ============================================================
        // Auto-generated by alkanes-wit-codegen. Do not edit manually.
        // ============================================================

        use alkanes_runtime::runtime::AlkaneResponder;
        use alkanes_runtime::message::MessageDispatch;
        use alkanes_support::cellpack::Cellpack;
        use alkanes_support::context::Context;
        use alkanes_support::id::AlkaneId;
        use alkanes_support::parcel::{AlkaneTransfer, AlkaneTransferParcel};
        use alkanes_support::response::CallResponse;
        use alkanes_support::wit_abi::{CellpackEncode, CellpackDecode};
        use anyhow::{anyhow, Result};

        #custom_types

        #contract_trait

        #dispatch

        #abi

        #clients

        #entry_points
    };

    Ok(GeneratedContract {
        module_code: tokens.to_string(),
    })
}

/// Generate code and write to a file.
pub fn generate_to_file(ir: &AlkaneContractIR, output_path: &Path) -> Result<()> {
    let generated = generate(ir)?;

    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    std::fs::write(output_path, &generated.module_code)?;
    Ok(())
}
