[package]
name = "alkanes-std-upgradeable-beacon"
version = "0.6.2"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
alkanes-runtime = { workspace = true, features = ["panic-hook"] }
alkanes-support = { workspace = true }
anyhow = { workspace = true }
bitcoin = { workspace = true }
metashrew-support = { workspace = true }
protorune-support = { workspace = true }
