//! EVM Bytecode Generator for Batch Payment Fetching
//!
//! This module uses huff-rs to programmatically generate EVM bytecode that fetches
//! and filters payments from the FrBTC contract in a single eth_call, replacing
//! the need for N individual eth_calls in a loop.
//!
//! The generated bytecode:
//! 1. Calls getPaymentsLength() via STATICCALL
//! 2. Loops backwards through payments, calling payments(idx) for each
//! 3. Filters based on cutoff_height and oldest_utxo_height
//! 4. Returns ABI-encoded Payment[] array

#[cfg(feature = "experimental-asm")]
use crate::Result;

#[cfg(feature = "experimental-asm")]
use huff_codegen::Codegen;

#[cfg(feature = "experimental-asm")]
use huff_utils::{
    ast::{AstSpan, Contract, MacroDefinition, Statement, StatementType, Label},
    evm::Opcode,
    evm_version::EVMVersion,
    bytes_util::str_to_bytes32,
};

#[cfg(feature = "experimental-asm")]
use std::sync::{Arc, Mutex};

/// Generate EVM bytecode for batch payment fetching
///
/// # Arguments
/// * `frbtc_address` - The FrBTC contract address (0x-prefixed hex string)
/// * `cutoff_height` - Skip payments with height > cutoff_height
/// * `oldest_utxo_height` - Break when reaching payment with height < oldest_utxo_height
///
/// # Returns
/// * Hex-encoded bytecode ready to use in eth_call {data: "0x..."}
#[cfg(feature = "experimental-asm")]
pub fn generate_batch_payment_fetcher_bytecode(
    frbtc_address: &str,
    cutoff_height: u64,
    oldest_utxo_height: u64,
) -> Result<String> {
    log::info!(
        "[BatchPaymentBytecode] Generating bytecode for frbtc={}, cutoff={}, oldest={}",
        frbtc_address,
        cutoff_height,
        oldest_utxo_height
    );

    // Build the Contract AST
    let contract = build_payment_fetcher_ast(frbtc_address, cutoff_height, oldest_utxo_height)?;

    // Generate bytecode using huff_codegen
    let bytecode = Codegen::generate_main_bytecode(&EVMVersion::default(), &contract, None)
        .map_err(|e| crate::AlkanesError::CodegenError(format!("Failed to generate bytecode: {:?}", e)))?;

    log::debug!("[BatchPaymentBytecode] Generated {} bytes of bytecode", bytecode.len() / 2);

    Ok(bytecode)
}

/// Build the Huff AST for the payment fetcher contract
#[cfg(feature = "experimental-asm")]
fn build_payment_fetcher_ast(
    frbtc_address: &str,
    cutoff_height: u64,
    oldest_utxo_height: u64,
) -> Result<Contract> {
    let mut statements = Vec::new();

    // Step 1: Call getPaymentsLength() on FrBTC
    statements.extend(build_get_payments_length_call(frbtc_address)?);

    // Step 2: Initialize loop (length - 1 -> idx)
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("01")?);  
    statements.push(push_opcode(Opcode::Sub));  // [length - 1]

    // Step 3: Initialize result offset at 0x80
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("80")?);  // [result_offset, idx]

    // Step 4: Create main loop label
    let loop_statements = build_payment_loop(frbtc_address, cutoff_height, oldest_utxo_height)?;
    let loop_label = Label {
        name: "loop_start".to_string(),
        inner: loop_statements,
        span: AstSpan(vec![]),
    };
    statements.push(Statement {
        ty: StatementType::Label(loop_label),
        span: AstSpan(vec![]),
    });

    // Step 5: Create finish label with return logic
    let return_statements = build_return_statements()?;
    let finish_label = Label {
        name: "finish".to_string(),
        inner: return_statements,
        span: AstSpan(vec![]),
    };
    statements.push(Statement {
        ty: StatementType::Label(finish_label),
        span: AstSpan(vec![]),
    });

    Ok(Contract {
        macros: vec![MacroDefinition {
            name: "MAIN".to_string(),
            decorator: None,
            parameters: vec![],
            statements,
            takes: 0,
            returns: 0,
            span: AstSpan(vec![]),
            outlined: false,
            test: false,
        }],
        invocations: vec![],
        imports: vec![],
        constants: Arc::new(Mutex::new(vec![])),
        errors: vec![],
        functions: vec![],
        events: vec![],
        tables: vec![],
    })
}

/// Build getPaymentsLength() STATICCALL
#[cfg(feature = "experimental-asm")]
fn build_get_payments_length_call(frbtc_address: &str) -> Result<Vec<Statement>> {
    let mut statements = Vec::new();

    // Prepare calldata: selector for getPaymentsLength() = 0x8b25f90e
    // Store selector at memory 0x00
    statements.push(push_opcode(Opcode::Push4));
    statements.push(push_literal("8b25f90e")?);  // getPaymentsLength() selector
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("00")?);
    statements.push(push_opcode(Opcode::Mstore));

    // STATICCALL setup: gas, address, argOffset, argSize, retOffset, retSize
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("20")?);  // retSize = 32 bytes
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("00")?);  // retOffset = 0x00
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("04")?);  // argSize = 4 bytes (selector only)
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("1c")?);  // argOffset = 28 (selector at 0x00, right-aligned in 32-byte word)
    
    // Push FrBTC address
    let addr_no_prefix = frbtc_address.strip_prefix("0x").unwrap_or(frbtc_address);
    statements.push(push_opcode(Opcode::Push20));
    statements.push(push_literal(addr_no_prefix)?);
    
    statements.push(push_opcode(Opcode::Push2));
    statements.push(push_literal("ffff")?);  // gas = 65535
    
    statements.push(push_opcode(Opcode::Staticcall));

    // Load the result (payments length) from memory 0x00
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("00")?);
    statements.push(push_opcode(Opcode::Mload));

    Ok(statements)
}

/// Build the payment loop using Huff labels for jump resolution
/// Stack at entry: [result_offset, idx]
#[cfg(feature = "experimental-asm")]
fn build_payment_loop(
    _frbtc_address: &str,
    _cutoff_height: u64,
    _oldest_utxo_height: u64,
) -> Result<Vec<Statement>> {
    let mut loop_body = Vec::new();

    // SIMPLIFIED VERSION: Just return immediately for now to test basic infrastructure
    // TODO: Implement full loop logic with proper label resolution
    
    // Check if idx is 0 (break loop)
    // Stack: [result_offset, idx]
    loop_body.push(push_opcode(Opcode::Dup2));     // [idx, result_offset, idx]
    loop_body.push(push_opcode(Opcode::Iszero));   // [idx==0, result_offset, idx]
    loop_body.push(Statement {
        ty: StatementType::LabelCall("finish".to_string()),
        span: AstSpan(vec![]),
    });
    loop_body.push(push_opcode(Opcode::Jumpi));
    
    // For now, just immediately jump to finish (skip loop)
    loop_body.push(Statement {
        ty: StatementType::LabelCall("finish".to_string()),
        span: AstSpan(vec![]),
    });
    loop_body.push(push_opcode(Opcode::Jump));
    
    Ok(loop_body)
}

// OLD IMPLEMENTATION - keeping for reference when we fix labels
#[cfg(feature = "experimental-asm")]
fn _build_payment_loop_full(
    frbtc_address: &str,
    cutoff_height: u64,
    oldest_utxo_height: u64,
) -> Result<Vec<Statement>> {
    let mut loop_body = Vec::new();

    // Check if idx is 0 (break loop)
    loop_body.push(push_opcode(Opcode::Dup2));
    loop_body.push(push_opcode(Opcode::Iszero));
    loop_body.push(Statement {
        ty: StatementType::LabelCall("finish".to_string()),
        span: AstSpan(vec![]),
    });
    loop_body.push(push_opcode(Opcode::Jumpi));

    // Prepare calldata: selector + idx
    loop_body.push(push_opcode(Opcode::Push4));
    statements.push(push_literal("87d81789")?);  // payments(uint256) selector
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("00")?);
    statements.push(push_opcode(Opcode::Mstore));

    // Store idx at 0x04
    statements.push(push_opcode(Opcode::Dup2));  // [idx, result_offset, idx]
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("04")?);
    statements.push(push_opcode(Opcode::Mstore));
    
    // STATICCALL: gas, address, argOffset, argSize, retOffset, retSize
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("a0")?);  // retSize = 160 bytes (Payment struct)
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("20")?);  // retOffset = 0x20
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("24")?);  // argSize = 36 bytes (4 + 32)
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("1c")?);  // argOffset = 28 (selector at 0x00)
    
    // Push FrBTC address
    let addr_no_prefix = frbtc_address.strip_prefix("0x").unwrap_or(frbtc_address);
    statements.push(push_opcode(Opcode::Push20));
    statements.push(push_literal(addr_no_prefix)?);
    
    statements.push(push_opcode(Opcode::Push2));
    statements.push(push_literal("ffff")?);  // gas
    statements.push(push_opcode(Opcode::Staticcall));
    statements.push(push_opcode(Opcode::Pop));  // Pop success boolean

    // Load payment.height from returndata
    // Payment struct layout: [txid(32), vout(32), value(32), recipient_offset(32), height(32), ...]
    // height is at offset 128 (0x80) from start of struct
    // Returndata is at 0x20, so height is at 0x20 + 0x80 = 0xa0
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("a0")?);
    statements.push(push_opcode(Opcode::Mload));  // [height, result_offset, idx]

    // Check if height > cutoff_height (skip if too new)
    statements.push(push_opcode(Opcode::Dup1));  // [height, height, result_offset, idx]
    statements.push(push_opcode(Opcode::Push8));
    statements.push(push_literal(&format!("{:016x}", cutoff_height))?);
    statements.push(push_opcode(Opcode::Gt));  // [height > cutoff, height, result_offset, idx]
    statements.push(push_opcode(Opcode::Push2));
    statements.push(push_literal("ffff")?);  // placeholder for CONTINUE address
    statements.push(push_opcode(Opcode::Jumpi));

    // Check if height < oldest_utxo_height (break if too old)
    statements.push(push_opcode(Opcode::Dup1));  // [height, height, result_offset, idx]
    statements.push(push_opcode(Opcode::Push8));
    statements.push(push_literal(&format!("{:016x}", oldest_utxo_height))?);
    statements.push(push_opcode(Opcode::Lt));  // [height < oldest, height, result_offset, idx]
    statements.push(push_opcode(Opcode::Push2));
    statements.push(push_literal("ffff")?);  // placeholder for FINISH address
    statements.push(push_opcode(Opcode::Jumpi));

    // Payment qualifies! Copy from 0x20 to result_offset (160 bytes)
    statements.push(push_opcode(Opcode::Pop));  // Pop height: [result_offset, idx]
    
    // Use a simple loop to copy 160 bytes (5 x 32-byte words)
    // Copy word by word from 0x20, 0x40, 0x60, 0x80, 0xa0
    for word_offset in (0x20u8..=0xa0).step_by(0x20) {
        statements.push(push_opcode(Opcode::Push1));
        statements.push(push_literal(&format!("{:02x}", word_offset))?);
        statements.push(push_opcode(Opcode::Mload));  // Load word
        statements.push(push_opcode(Opcode::Dup2));   // [result_offset, word, result_offset, idx]
        statements.push(push_opcode(Opcode::Mstore)); // Store at result_offset
        
        // Increment result_offset by 32
        if word_offset < 0xa0 {
            statements.push(push_opcode(Opcode::Push1));
            statements.push(push_literal("20")?);
            statements.push(push_opcode(Opcode::Add));
        }
    }
    
    // result_offset is now updated, continue to next payment
    // CONTINUE label (JUMPDEST)
    statements.push(push_opcode(Opcode::Jumpdest));  // continue label
    
    // Decrement idx
    statements.push(push_opcode(Opcode::Swap1));  // [idx, result_offset]
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("01")?);
    statements.push(push_opcode(Opcode::Sub));  // [idx-1, result_offset]
    statements.push(push_opcode(Opcode::Swap1));  // [result_offset, idx-1]
    
    // Jump back to loop start
    statements.push(push_opcode(Opcode::Push2));
    statements.push(push_literal("ffff")?);  // placeholder for LOOP_START address
    statements.push(push_opcode(Opcode::Jump));

    // FINISH label (JUMPDEST) 
    statements.push(push_opcode(Opcode::Jumpdest));  // finish label
    
    // Clean up stack before return: [result_offset, idx] or variations
    // We need to format return data properly
    
    Ok(statements)
}

/// Build return statements for ABI-encoded Payment[] array
/// Stack at entry: [result_offset, idx] where result_offset points to end of collected data
#[cfg(feature = "experimental-asm")]
fn build_return_statements() -> Result<Vec<Statement>> {
    let mut statements = Vec::new();

    // Calculate size: result_offset - 0x80 (start offset)
    // Stack: [result_offset, idx]
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("80")?);  // start offset
    statements.push(push_opcode(Opcode::Swap1));  // [result_offset, 0x80, idx]
    statements.push(push_opcode(Opcode::Sub));     // [size, idx]
    
    // Return from 0x80 with calculated size
    statements.push(push_opcode(Opcode::Push1));
    statements.push(push_literal("80")?);  // offset
    statements.push(push_opcode(Opcode::Return));

    Ok(statements)
}

/// Helper: Create a literal statement
#[cfg(feature = "experimental-asm")]
fn push_literal(hex_value: &str) -> Result<Statement> {
    let padded = format!("{:0>64}", hex_value);
    Ok(Statement {
        ty: StatementType::Literal(str_to_bytes32(&padded)),
        span: AstSpan(vec![]),
    })
}

/// Helper: Create an opcode statement
#[cfg(feature = "experimental-asm")]
fn push_opcode(opcode: Opcode) -> Statement {
    Statement {
        ty: StatementType::Opcode(opcode),
        span: AstSpan(vec![]),
    }
}

#[cfg(test)]
#[cfg(feature = "experimental-asm")]
mod tests {
    use super::*;

    #[test]
    fn test_generate_bytecode() {
        let bytecode = generate_batch_payment_fetcher_bytecode(
            "0x1234567890123456789012345678901234567890",
            1000,
            500,
        );

        assert!(bytecode.is_ok());
        let hex = bytecode.unwrap();
        assert!(!hex.is_empty());
        println!("Generated bytecode: 0x{}", hex);
    }
}
