//! EVM Bytecode Generator for Batch Payment Fetching
//!
//! This module uses emasm-rs to programmatically generate EVM bytecode that fetches
//! and filters payments from the FrBTC contract in a single eth_call, replacing
//! the need for N individual eth_calls in a loop.
//!
//! The generated bytecode:
//! 1. Calls getPaymentsLength() via STATICCALL to get the total payment count
//! 2. Loops backwards through payments, calling payments(idx) for each
//! 3. Filters based on cutoff_height - stops when reaching a payment older than cutoff
//! 4. Returns ABI-encoded Payment[] array

#[cfg(feature = "experimental-asm")]
use crate::Result;

#[cfg(feature = "experimental-asm")]
use emasm::{evm_asm_interpolator, EVMEncodable};

#[cfg(feature = "experimental-asm")]
use alloy_primitives::Address;

/// Generate EVM bytecode for batch payment fetching
///
/// # Arguments
/// * `frbtc_address` - The FrBTC contract address (20 bytes)
/// * `cutoff_height` - Stop iteration when reaching payment with height < cutoff_height
///
/// # Returns
/// * Hex-encoded bytecode ready to use in eth_call {data: "0x..."}
#[cfg(feature = "experimental-asm")]
pub fn generate_batch_payment_fetcher_bytecode(
    frbtc_address: &str,
    cutoff_height: u64,
) -> Result<String> {
    log::info!(
        "[BatchPaymentBytecode] Generating bytecode for frbtc={}, cutoff={}",
        frbtc_address,
        cutoff_height
    );

    // Parse the address
    let addr_bytes = parse_address(frbtc_address)?;
    
    // Create the interpolator with placeholders for address and cutoff height
    let builder = evm_asm_interpolator!([
        // Call getPaymentsLength() -> uint256
        // Prepare calldata: selector at memory 0x00
        0x8b25f90e,          // selector for getPaymentsLength() as a 4-byte integer
        0x00,
        "mstore",
        
        // STATICCALL(gas, address, argsOffset, argsSize, retOffset, retSize)
        0x20,                // retSize = 32 bytes
        0x00,                // retOffset = 0x00
        0x04,                // argsSize = 4 bytes (selector only)
        0x1c,                // argsOffset = 28 (selector right-aligned at 0x00)
        &[0],                // FrBTC address placeholder
        0xffff,              // gas = 65535
        "staticcall",
        "pop",               // Pop success boolean
        
        // Load the result (payments length) from memory 0x00
        0x00,
        "mload",
        
        // Stack: [payments_length]
        // This is our loop counter (idx)
        
        // Jump to loop_start
        "loop_start",
        "jump",
        
        // Loop: iterate backwards from payments_length to 0
        ["loop_start", [
            // Stack: [idx]
            
            // Check if idx == 0, if so jump to finish
            "dup1",          // [idx, idx]
            "iszero",        // [idx==0, idx]
            "finish",        // [finish_addr, idx==0, idx]
            "jumpi",         // Jump to finish if idx==0
            
            // Stack: [idx]
            // Decrement idx
            0x01,
            "sub",           // [idx-1]
            
            // TODO: Call payments(idx-1) and check height
            // For now, just loop back
            "loop_start",
            "jump"
        ]],
        
        // Finish: return empty result for now
        ["finish", [
            "pop",           // Pop idx=0
            0x00,            // offset
            0x00,            // size
            "return"
        ]]
    ]);
    
    // Generate bytecode with the actual address
    let bytecode = builder(Box::new(addr_bytes));
    
    let hex = hex::encode(&bytecode);
    log::debug!("[BatchPaymentBytecode] Generated {} bytes of bytecode", bytecode.len());
    
    Ok(format!("0x{}", hex))
}

/// Parse an Ethereum address from hex string to alloy Address
#[cfg(feature = "experimental-asm")]
fn parse_address(addr: &str) -> Result<Address> {
    let addr_no_prefix = addr.strip_prefix("0x").unwrap_or(addr);
    if addr_no_prefix.len() != 40 {
        return Err(crate::AlkanesError::Other(format!(
            "Address must be 40 hex characters, got {}",
            addr_no_prefix.len()
        )));
    }
    
    let bytes = hex::decode(addr_no_prefix)
        .map_err(|e| crate::AlkanesError::Other(format!("Invalid hex: {}", e)))?;
    
    if bytes.len() != 20 {
        return Err(crate::AlkanesError::Other(format!(
            "Address must be 20 bytes, got {}",
            bytes.len()
        )));
    }
    
    let mut addr_bytes = [0u8; 20];
    addr_bytes.copy_from_slice(&bytes);
    Ok(Address::from(addr_bytes))
}

#[cfg(test)]
#[cfg(feature = "experimental-asm")]
mod tests {
    use super::*;

    #[test]
    fn test_generate_bytecode() {
        let bytecode = generate_batch_payment_fetcher_bytecode(
            "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
            1000,
        );

        assert!(bytecode.is_ok());
        let hex = bytecode.unwrap();
        assert!(hex.starts_with("0x"));
        assert!(!hex.is_empty());
        println!("Generated bytecode: {}", hex);
    }
    
    #[test]
    fn test_parse_address() {
        let addr = parse_address("0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0");
        assert!(addr.is_ok());
        
        let address = addr.unwrap();
        let bytes = address.as_slice();
        assert_eq!(bytes.len(), 20);
        assert_eq!(bytes[0], 0x9f);
    }
}
