//! Solidity-compiled FrBTCQuery contract bytecode
//!
//! This module provides the bytecode from the compiled FrBTCQuery.sol contract
//! which fetches all payments from the FrBTC contract in a single eth_call.
//!
//! The contract ABI encodes the frbtc address into constructor args and
//! returns all payments as ABI-encoded Payment[] array.

use crate::Result;
use alloy_primitives::Address;

/// Raw bytecode from FrBTCQuery.sol compilation
/// This is the "bytecode.object" from the Foundry build output
const FRBTC_QUERY_BYTECODE: &str = include_str!("FrBTCQuery.bytecode.hex");

/// Generate the deployment bytecode for FrBTCQuery with filtering parameters encoded
///
/// The constructor takes three arguments:
/// - address frbtc: The FrBTC contract address
/// - uint256 cutoffHeight: Maximum block height (payments with height > cutoff are excluded)
/// - uint256 oldestHeight: Minimum block height (payments with height < oldest are excluded)
///
/// # Arguments
/// * `frbtc_address` - The FrBTC contract address (0x-prefixed hex)
/// * `cutoff_height` - Maximum block height to include
/// * `oldest_height` - Minimum block height to include
///
/// # Returns
/// * Hex-encoded bytecode ready to use in eth_call {data: "0x..."}
pub fn generate_frbtc_query_bytecode(
    frbtc_address: &str,
    cutoff_height: u64,
    oldest_height: u64,
) -> Result<String> {
    log::info!(
        "[SolQueryBytecode] Generating FrBTCQuery bytecode for frbtc={}, cutoff={}, oldest={}",
        frbtc_address, cutoff_height, oldest_height
    );

    // Parse the address
    let addr = parse_address(frbtc_address)?;

    // Get the base bytecode (strip 0x prefix if present, and trim whitespace)
    let base_bytecode = FRBTC_QUERY_BYTECODE
        .trim()
        .strip_prefix("0x")
        .unwrap_or(FRBTC_QUERY_BYTECODE.trim());

    // ABI-encode constructor arguments:
    // address (32 bytes, left-padded) + uint256 cutoffHeight + uint256 oldestHeight
    let mut encoded_args = Vec::new();

    // Encode address (left-padded to 32 bytes)
    let mut addr_bytes = [0u8; 32];
    addr_bytes[12..32].copy_from_slice(addr.as_slice());
    encoded_args.extend_from_slice(&addr_bytes);

    // Encode cutoffHeight (uint256, big-endian)
    let mut cutoff_bytes = [0u8; 32];
    cutoff_bytes[24..32].copy_from_slice(&cutoff_height.to_be_bytes());
    encoded_args.extend_from_slice(&cutoff_bytes);

    // Encode oldestHeight (uint256, big-endian)
    let mut oldest_bytes = [0u8; 32];
    oldest_bytes[24..32].copy_from_slice(&oldest_height.to_be_bytes());
    encoded_args.extend_from_slice(&oldest_bytes);

    // Concatenate: base bytecode + encoded arguments
    let full_bytecode = format!("0x{}{}", base_bytecode, hex::encode(&encoded_args));

    log::info!(
        "[SolQueryBytecode] Generated {} bytes of bytecode (base: {}, args: {})",
        full_bytecode.len() / 2 - 1, // -1 for 0x prefix
        base_bytecode.len() / 2,
        encoded_args.len()
    );

    Ok(full_bytecode)
}

/// Parse an Ethereum address from hex string
fn parse_address(addr: &str) -> Result<Address> {
    let addr_no_prefix = addr.strip_prefix("0x").unwrap_or(addr);
    if addr_no_prefix.len() != 40 {
        return Err(crate::AlkanesError::Other(format!(
            "Address must be 40 hex characters, got {}",
            addr_no_prefix.len()
        )));
    }

    let bytes = hex::decode(addr_no_prefix)
        .map_err(|e| crate::AlkanesError::Other(format!("Invalid hex: {}", e)))?;

    if bytes.len() != 20 {
        return Err(crate::AlkanesError::Other(format!(
            "Address must be 20 bytes, got {}",
            bytes.len()
        )));
    }

    let mut addr_bytes = [0u8; 20];
    addr_bytes.copy_from_slice(&bytes);
    Ok(Address::from(addr_bytes))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_bytecode() {
        let bytecode = generate_frbtc_query_bytecode(
            "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
            1000000,  // cutoff_height
            100000,   // oldest_height
        );

        assert!(bytecode.is_ok());
        let hex = bytecode.unwrap();
        assert!(hex.starts_with("0x"));
        // Bytecode should end with the encoded constructor args (addr + 2 uint256s)
        // Total: 96 bytes = 192 hex chars for the 3 constructor args
        assert!(hex.len() > 200);
        println!("Generated bytecode length: {} bytes", hex.len() / 2);
    }

    #[test]
    fn test_parse_address() {
        let addr = parse_address("0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0");
        assert!(addr.is_ok());
    }
}
