[package]
name = "alkanes-std-owned-token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
test = []

[dependencies]
alkanes-support = { path = "../alkanes-support" }
alkanes-runtime = { path = "../alkanes-runtime" }
metashrew-support = { path = "../../reference/metashrew/metashrew-support" }
protorune-support = { path = "../protorune-support" }
ordinals = { path = "../ordinals" }
anyhow = "1.0.94"
bitcoin = { version = "0.32.4", features = ["rand"] }
