#!/bin/bash
# Set up a GCP service account with Owner role for the pkg-alkanes-build project
# and generate a .pkgenv file to source for targeting that project.
#
# Prerequisites:
#   - gcloud CLI authenticated with permissions to create service accounts and keys
#   - jq installed
#
# Usage:
#   ./pkg/setup-sa.sh
#   source ~/.pkgenv

set -euo pipefail

PROJECT="pkg-alkanes-build"
SA_NAME="pkg-owner-sa"
SA_EMAIL="${SA_NAME}@${PROJECT}.iam.gserviceaccount.com"
KEY_FILE="${HOME}/pkg-sa-key.json"
ENV_FILE="${HOME}/.pkgenv"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}=== Service Account Setup for ${PROJECT} ===${NC}"

# Ensure gcloud is available
if ! command -v gcloud &>/dev/null; then
  echo -e "${YELLOW}Error: gcloud CLI is not installed or not in PATH${NC}"
  exit 1
fi

# Set the target project
echo "Setting active project to ${PROJECT}..."
gcloud config set project "${PROJECT}"

# Create service account if it doesn't already exist
if gcloud iam service-accounts describe "${SA_EMAIL}" --project="${PROJECT}" &>/dev/null; then
  echo -e "${YELLOW}Service account ${SA_EMAIL} already exists, skipping creation${NC}"
else
  echo "Creating service account ${SA_NAME}..."
  gcloud iam service-accounts create "${SA_NAME}" \
    --project="${PROJECT}" \
    --display-name="Package Registry Owner SA"
  echo -e "${GREEN}✓ Created service account${NC}"
fi

# Grant Owner role
echo "Granting roles/owner to ${SA_EMAIL}..."
gcloud projects add-iam-policy-binding "${PROJECT}" \
  --member="serviceAccount:${SA_EMAIL}" \
  --role="roles/owner" \
  --condition=None \
  --quiet
echo -e "${GREEN}✓ Granted Owner role${NC}"

# Generate a new JSON key
echo "Generating service account key..."
gcloud iam service-accounts keys create "${KEY_FILE}" \
  --iam-account="${SA_EMAIL}" \
  --project="${PROJECT}"
echo -e "${GREEN}✓ Key written to ${KEY_FILE}${NC}"

# Write .pkgenv
cat > "${ENV_FILE}" <<EOF
# Source this file to target the pkg-alkanes-build GCP project.
# Generated by pkg/setup-sa.sh

export GOOGLE_APPLICATION_CREDENTIALS="${KEY_FILE}"
export GCLOUD_PROJECT="${PROJECT}"
export CLOUDSDK_CORE_PROJECT="${PROJECT}"
export GCP_PROJECT="${PROJECT}"
EOF

echo -e "${GREEN}✓ Wrote ${ENV_FILE}${NC}"

echo ""
echo -e "${GREEN}=== Setup Complete ===${NC}"
echo ""
echo "To activate:"
echo "  source ${ENV_FILE}"
echo ""
echo "This sets:"
echo "  GOOGLE_APPLICATION_CREDENTIALS → ${KEY_FILE}"
echo "  GCLOUD_PROJECT / CLOUDSDK_CORE_PROJECT / GCP_PROJECT → ${PROJECT}"
echo ""
echo -e "${YELLOW}Keep ${KEY_FILE} safe and do not commit it to version control.${NC}"
